use crate::elements::stats::Stats;

#[derive(Clone, Copy)]
pub enum Race {
    Human,
    Elf,
    Dwarf,
    Orc,
    Undead,
    Halfling,
    Fairy,
    Dragonborn,
    Demon,
    Giant,
    Troll,
    Dryad,
}

impl Race {
    pub fn attributes(&self) -> Stats {
        match self {
            Race::Human => Stats {
                strength: 6,
                dexterity: 6,
                charisma: 6,
                intelligence: 6,
                constitution: 6,
                wisdom: 5,
                lucky: 5,
            },
            Race::Elf => Stats {
                strength: 4,
                dexterity: 7,
                charisma: 6,
                intelligence: 7,
                constitution: 4,
                wisdom: 7,
                lucky: 5,
            },
            Race::Dwarf => Stats {
                strength: 7,
                dexterity: 4,
                charisma: 4,
                intelligence: 5,
                constitution: 8,
                wisdom: 6,
                lucky: 6,
            },
            Race::Orc => Stats {
                strength: 8,
                dexterity: 5,
                charisma: 3,
                intelligence: 4,
                constitution: 8,
                wisdom: 5,
                lucky: 7,
            },
            Race::Undead => Stats {
                strength: 5,
                dexterity: 5,
                charisma: 3,
                intelligence: 6,
                constitution: 7,
                wisdom: 7,
                lucky: 7,
            },
            Race::Halfling => Stats {
                strength: 3,
                dexterity: 7,
                charisma: 6,
                intelligence: 5,
                constitution: 5,
                wisdom: 5,
                lucky: 9,
            },
            Race::Fairy => Stats {
                strength: 2,
                dexterity: 9,
                charisma: 6,
                intelligence: 6,
                constitution: 3,
                wisdom: 7,
                lucky: 7,
            },
            Race::Dragonborn => Stats {
                strength: 7,
                dexterity: 5,
                charisma: 5,
                intelligence: 5,
                constitution: 8,
                wisdom: 5,
                lucky: 5,
            },
            Race::Demon => Stats {
                strength: 7,
                dexterity: 6,
                charisma: 6,
                intelligence: 6,
                constitution: 6,
                wisdom: 4,
                lucky: 5,
            },
            Race::Giant => Stats {
                strength: 9,
                dexterity: 4,
                charisma: 3,
                intelligence: 3,
                constitution: 9,
                wisdom: 6,
                lucky: 6,
            },
            Race::Troll => Stats {
                strength: 8,
                dexterity: 4,
                charisma: 3,
                intelligence: 4,
                constitution: 9,
                wisdom: 6,
                lucky: 6,
            },
            Race::Dryad => Stats {
                strength: 4,
                dexterity: 7,
                charisma: 6,
                intelligence: 6,
                constitution: 4,
                wisdom: 7,
                lucky: 6,
            },
        }
    }
}